language: java

script: mvn clean install

jdk:
    - oraclejdk7
    - openjdk7

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn verify -Ptravis,with-lib
  - mvn jacoco:report -Ptravis
  - mvn -N coveralls:jacoco -Ptravis