language: java

script:
  - mvn clean package -Pwith-lib,jacoco

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com

after_success:
  - mvn jacoco:report -pl lib
  - mvn -N coveralls:jacoco